// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_youre_a_natural = "CgkI5sOy6N8UEAIQAg"; // <GPGSID>
        public const string leaderboard_total_wins = "CgkI5sOy6N8UEAIQBg"; // <GPGSID>
        public const string achievement_clutching_out_the_win = "CgkI5sOy6N8UEAIQBQ"; // <GPGSID>
        public const string achievement_you_want_a_medal_for_pushing_a_button = "CgkI5sOy6N8UEAIQBw"; // <GPGSID>
        public const string achievement_its_the_end_of_the_world = "CgkI5sOy6N8UEAIQBA"; // <GPGSID>
        public const string achievement_damn_youre_really_good_at_pushing_that_button = "CgkI5sOy6N8UEAIQCA"; // <GPGSID>
        public const string achievement_just_warming_up = "CgkI5sOy6N8UEAIQAQ"; // <GPGSID>
        public const string achievement_sorry_i_cant_hear_you_with_all_this_winning = "CgkI5sOy6N8UEAIQAw"; // <GPGSID>

}

